application: map-of-life
version: canary
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

- url: /js
  static_dir: js

- url: /
  script: app.application

- url: /.*
  script: app.application


